redis:
    image: redis
    volumes:
        - /home/data/vj_redis:/data

mysql:
    image: mysql
    volumes:
        - /home/data/vj_mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD={YOUR_PASSWORD}

openvj_server:
    image: openvj
    volumes:
        - /home/openvj:/code
    links:
        - redis:redis
        - mysql:mysql
    ports:
        - "127.0.0.1:8090:8080"
    environment:
        - vj_env=server
        - MYSQL_ENV_MYSQL_USER=root