# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('is_valid', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='OJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('robot', models.CharField(max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'oj',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('submit_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('memory_limit', models.IntegerField(blank=True, null=True)),
                ('input_description', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
                ('samples', models.TextField(blank=True, null=True)),
                ('spj', models.BooleanField(default=False)),
                ('hint', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(0, 'Done'), (1, 'Crawling'), (2, 'Failed')])),
                ('task_id', models.CharField(max_length=40)),
                ('oj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.OJ')),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RobotStatusInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_info', models.TextField()),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'robot_status_info',
            },
        ),
        migrations.CreateModel(
            name='RobotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_login_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Occupied'), (0, 'Free')])),
                ('oj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.OJ')),
            ],
            options={
                'db_table': 'robot_user',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('cpu_time', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('info', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Problem')),
                ('robot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.RobotUser')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.AddField(
            model_name='robotstatusinfo',
            name='robot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.RobotUser'),
        ),
        migrations.AlterUniqueTogether(
            name='robotuser',
            unique_together=set([('oj', 'username')]),
        ),
    ]
