# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 8, 56, 43, 529386, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 9, 8, 56, 47, 673690, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
