# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160309_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='origin_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
