# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_problem_origin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='api_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='server.APIKey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 9, 11, 11, 38, 878862, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'done'), (server.models.SubmissionStatus, 'crawling'), (3, 'failed')], default=1),
            preserve_default=False,
        ),
    ]
