# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20160309_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.IntegerField(choices=[('C', 0), ('CPP', 1), ('Java', 2)], default=1),
            preserve_default=False,
        ),
    ]
