# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_submission_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='origin_submission_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.IntegerField(choices=[(0, 'C'), (1, 'CPP'), (2, 'Java')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.IntegerField(choices=[(0, 'accepted'), (6, 'wrong_answer'), (4, 'compiler_error'), (5, 'format_error'), (3, 'memory_limit_exceeded'), (2, 'time_limit_exceeded'), (1, 'runtime_error'), (7, 'system_error'), (8, 'waiting')]),
        ),
    ]
