# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20160309_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False),
        ),
    ]
