# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20160309_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='task_id',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='id',
            field=models.CharField(db_index=True, default=server.models.rand_str, max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.CharField(db_index=True, default=server.models.rand_str, max_length=40, primary_key=True, serialize=False),
        ),
    ]
