# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20160309_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='task_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='get_result_task_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submit_task_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='cpu_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='robot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.RobotUser'),
        ),
    ]
