# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_submission_dispatcher_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionWaitingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_waiting_queue',
            },
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='dispatcher_task_id',
            new_name='task_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='get_result_task_id',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default=server.models.rand_str, max_length=40),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'done'), (server.models.SubmissionStatus, 'crawling')]),
        ),
        migrations.AddField(
            model_name='submissionwaitingqueue',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Submission'),
        ),
    ]
